server:
  address: 0.0.0.0
  port: ${PORT:80}
planny:
  cloud-enabled: true
  access-password: ${PLANNY_ACCESS_PASSWORD}
  allowed-origins: ${PLANNY_ALLOWED_ORIGINS:}
  database-url: ${PLANNY_DB_URL:${DATABASE_URL:${POSTGRES_URL:}}}
  database-user: ${PLANNY_DB_USER:}
  database-password: ${PLANNY_DB_PASSWORD:}
